"""empty message

Revision ID: 31e0e73c8369
Revises: d92c3651c15d
Create Date: 2023-02-23 14:40:29.667714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31e0e73c8369"
down_revision = "d92c3651c15d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reg_date", sa.DateTime(), nullable=True))

    with op.batch_alter_table("shareholder", schema=None) as batch_op:
        batch_op.add_column(sa.Column("founder", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("physical_person", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shareholder", schema=None) as batch_op:
        batch_op.drop_column("physical_person")
        batch_op.drop_column("founder")

    with op.batch_alter_table("company", schema=None) as batch_op:
        batch_op.drop_column("reg_date")

    # ### end Alembic commands ###
