"""empty message

Revision ID: 383de3ef5bd5
Revises: 31e0e73c8369
Create Date: 2023-03-03 16:53:58.903048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "383de3ef5bd5"
down_revision = "31e0e73c8369"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "physical_person",
        sa.Column("firstName", sa.String(length=100), nullable=True),
        sa.Column("lastName", sa.String(length=100), nullable=True),
        sa.Column("reg_code", sa.String(length=11), nullable=False),
        sa.PrimaryKeyConstraint("reg_code"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("physical_person")
    # ### end Alembic commands ###
