"""empty message

Revision ID: abbbedbad239
Revises: 
Create Date: 2023-02-21 08:32:11.585417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abbbedbad239"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("reg_code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("reg_code"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company")
    # ### end Alembic commands ###
